### ISSUE TITLE
Processing a single image

### ISSUE THREAD

**Issue by mk1922** [wsh312/S2Dnet#4]
Hey there!
Your results look very promising so I tried to process a single image through the CycleGAN but I can't figure out how to do that.
The command "test.py --dataroot ./Image --name S2Dnet --model cycle_gan --logroot 0 --which_model_netG unet_512_Re1" throws an error because I didn't define some directorys according to my system.
Can you explain where and how to set the parameters to simply process a single image through your pretrained network?
Thank you very much!

**Comment by wsh312** [comment]
Hello, thanks for your interest!
At the moment, you should train your own CycleGAN from scratch using our single view dataset.
It is on my to-do list to train a single view CycleGAN (using re-convolution to remove checkerboard artifacts) so that people can use it directly.
I will update the git as soon as I finish that ;)

**Comment by mk1922** [comment]
Thank you very much for your help! I will give it a try.
